[workspace]
members = ["cosmos_sdk_proto", "proto_build", "wasmd_proto"]
resolver = "2"

[workspace.dependencies]
env_logger = "0.11"
log = "0.4"
prost = "0.12"
prost-build = "0.12"
prost-types = "0.12"
tonic = {version = "0.10", features = ["gzip"]}
tonic-build = "0.10"
