[workspace]
members = ["cosmos_sdk_proto", "proto_build"]
resolver = "2"

[workspace.dependencies]
env_logger = "0.11"
log = "0.4"
prost = "0.13"
prost-build = "0.13"
prost-types = "0.13"
tonic = "0.12"
tonic-build = "0.12"
